name: Release

on:
  [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-cpp:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build cpp
        run: xmake -y

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux/x86_64/release/AkashaDDNS
  
  build-windows-cpp:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: xmake-io/xmake#branch@dev
      
      - name: install MinGW via chocolatey
        run: choco install mingw

      - name: use clang-cl
        run: xmake f -p mingw -y
        
      - name: build cpp
        run: xmake -y

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/x64/release/AkashaDDNS.exe

  build-linux-rust:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: cargo build --release

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/AkashaDDNS-rust
  
  build-windows-rust:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: cargo build --release

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/AkashaDDNS-rust.exe

  
