name: Release

on:
  [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: build cpp
        run: xmake -y

      - name: release
        uses: OpenSumeru/AkashaDDNS@main
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux/x86_64/release/AkashaDDNS
  
  build-windows:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          
      - name: build cpp
        run: xmake -y

      - name: release
        uses: OpenSumeru/AkashaDDNS@main
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/x64/release/AkashaDDNS.exe
        

  
